In [7]:
import box_lib
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from IPython.core.debugger import set_trace
import numpy as np



def main():
  train_ds = box_lib.BoxDataset("data/sample/train.txt")
  train_dl = DataLoader(train_ds, batch_size=18, shuffle=True, num_workers=4)

  model = box_lib.Boxes(6,4)
  criterion = nn.MSELoss()
  optimizer = torch.optim.Adam(model.parameters(), lr=0.001)


  N_EPOCHS = 200

  for epoch in range(N_EPOCHS):

      # Train
      model.train()  # IMPORTANT

      running_loss, correct = 0.0, 0
      for X, y in train_dl:
        #set_trace()
        #X, y = X.to(device), y.to(device)

        optimizer.zero_grad()
        with torch.set_grad_enabled(True):
          y_ = model(X)
          loss = criterion(y_, y)
          print(loss)

        loss.backward()

        for param in model.parameters():
          print(param.grad.data.sum())
        print(model.boxes[0])
        optimizer.step()

        # Statistics
        print("    batch loss: "+str(loss.item()))
        running_loss += loss.item() * X.shape[0]

      print("  Train Loss: "+str(running_loss / len(train_dl.dataset)))
      print("  Train Acc:  "+str(correct / len(train_dl.dataset)))


if __name__ == "__main__":
  main()

tensor([[0.7087, 0.7627, 0.4170, 0.0511],
        [0.5845, 0.5762, 0.5071, 0.1019],
        [0.7087, 0.7627, 0.5071, 0.1019],
        [0.8076, 0.3786, 0.8455, 0.9175],
        [0.4579, 0.9263, 0.5071, 0.4457],
        [0.3775, 0.9263, 0.8455, 0.4457],
        [0.5845, 0.3786, 0.8455, 0.2079],
        [0.8076, 0.3786, 0.8455, 0.9175],
        [0.3775, 0.9263, 0.8455, 0.4457],
        [0.7087, 0.7627, 0.5071, 0.1019],
        [0.7087, 0.9263, 0.4170, 0.4457],
        [0.8076, 0.9263, 0.3073, 0.9175],
        [0.8076, 0.9263, 0.3073, 0.9175],
        [0.8076, 0.7627, 0.4170, 0.9175],
        [0.8076, 0.5762, 0.5071, 0.9175],
        [0.7087, 0.7627, 0.8455, 0.2079],
        [0.4579, 0.5762, 0.8455, 0.2079],
        [0.5845, 0.3786, 0.8455, 0.2079]], grad_fn=<MaxBackward2>)
tensor([[0.9098, 0.4481, 0.5879, 0.6408],
        [0.9360, 0.4481, 0.5879, 0.1092],
        [0.9098, 0.6767, 0.6130, 0.1092],
        [0.9525, 0.3813, 0.3577, 0.3821],
        [0.4679, 0.6767, 0.6130, 0.1092],
        [

tensor([[0.7137, 0.7578, 0.5027, 0.0979],
        [0.8108, 0.7578, 0.4219, 0.9126],
        [0.3725, 0.9214, 0.8411, 0.4407],
        [0.5894, 0.3834, 0.8411, 0.2034],
        [0.3725, 0.9214, 0.8411, 0.4407],
        [0.4535, 0.5719, 0.8411, 0.2034],
        [0.8108, 0.5719, 0.5027, 0.9126],
        [0.7137, 0.7578, 0.8411, 0.2034],
        [0.7137, 0.7578, 0.5027, 0.0979],
        [0.8108, 0.3834, 0.8411, 0.9126],
        [0.8108, 0.3834, 0.8411, 0.9126],
        [0.4535, 0.9214, 0.5027, 0.4407],
        [0.8108, 0.9214, 0.3074, 0.9126],
        [0.5894, 0.5719, 0.5027, 0.0979],
        [0.7137, 0.7578, 0.4219, 0.0560],
        [0.7137, 0.9214, 0.4219, 0.4407],
        [0.5894, 0.3834, 0.8411, 0.2034],
        [0.8108, 0.9214, 0.3074, 0.9126]], grad_fn=<MaxBackward2>)
tensor([[0.9049, 0.6810, 0.6174, 0.1133],
        [0.9049, 0.3860, 0.3621, 0.6456],
        [0.4728, 0.8838, 0.8940, 0.3869],
        [0.9406, 0.4531, 0.5830, 0.3869],
        [0.4728, 0.8838, 0.8940, 0.3869],
        [

tensor([[0.3676, 0.9170, 0.8378, 0.4360],
        [0.5942, 0.5689, 0.4997, 0.0954],
        [0.7186, 0.7531, 0.8378, 0.2001],
        [0.8106, 0.3874, 0.8378, 0.9084],
        [0.4507, 0.5689, 0.8378, 0.2001],
        [0.8106, 0.9170, 0.3118, 0.9084],
        [0.4507, 0.9170, 0.4997, 0.4360],
        [0.5942, 0.3874, 0.8378, 0.2001],
        [0.7186, 0.9170, 0.4267, 0.4360],
        [0.7186, 0.7531, 0.4267, 0.0607],
        [0.8106, 0.7531, 0.4267, 0.9084],
        [0.5942, 0.3874, 0.8378, 0.2001],
        [0.3676, 0.9170, 0.8378, 0.4360],
        [0.8106, 0.5689, 0.4997, 0.9084],
        [0.7186, 0.7531, 0.4997, 0.0954],
        [0.7186, 0.7531, 0.4997, 0.0954],
        [0.8106, 0.9170, 0.3118, 0.9084],
        [0.8106, 0.3874, 0.8378, 0.9084]], grad_fn=<MaxBackward2>)
tensor([[0.4773, 0.8887, 0.8986, 0.3908],
        [0.9286, 0.4575, 0.5783, 0.1157],
        [0.9000, 0.8646, 0.7952, 0.3908],
        [0.9437, 0.3898, 0.3651, 0.3908],
        [0.9286, 0.6839, 0.6203, 0.1157],
        [

tensor([[0.8093, 0.5669, 0.4977, 0.9050],
        [0.7233, 0.7488, 0.4312, 0.0650],
        [0.8093, 0.3907, 0.8354, 0.9050],
        [0.7233, 0.7488, 0.4977, 0.0939],
        [0.8093, 0.3907, 0.8354, 0.9050],
        [0.7233, 0.9131, 0.4312, 0.4316],
        [0.5987, 0.5669, 0.4977, 0.0939],
        [0.7233, 0.7488, 0.4977, 0.0939],
        [0.3628, 0.9131, 0.8354, 0.4316],
        [0.4487, 0.9131, 0.4977, 0.4316],
        [0.5987, 0.3907, 0.8354, 0.1977],
        [0.7233, 0.7488, 0.8354, 0.1977],
        [0.8093, 0.7488, 0.4312, 0.9050],
        [0.5987, 0.3907, 0.8354, 0.1977],
        [0.3628, 0.9131, 0.8354, 0.4316],
        [0.8093, 0.9131, 0.3165, 0.9050],
        [0.8093, 0.9131, 0.3165, 0.9050],
        [0.4487, 0.5669, 0.8354, 0.1977]], grad_fn=<MaxBackward2>)
tensor([[0.9265, 0.3928, 0.3672, 0.1173],
        [0.8954, 0.4611, 0.5740, 0.6522],
        [0.9406, 0.3928, 0.3672, 0.3937],
        [0.8954, 0.6859, 0.6224, 0.1173],
        [0.9406, 0.3928, 0.3672, 0.3937],
        [

tensor([[0.7278, 0.7450, 0.4963, 0.0929],
        [0.4473, 0.5655, 0.8337, 0.1958],
        [0.7278, 0.7450, 0.4963, 0.0929],
        [0.6030, 0.5655, 0.4963, 0.0929],
        [0.8077, 0.5655, 0.4963, 0.9023],
        [0.8077, 0.9099, 0.3212, 0.9023],
        [0.6030, 0.3932, 0.8337, 0.1958],
        [0.8077, 0.9099, 0.3212, 0.9023],
        [0.8077, 0.3932, 0.8337, 0.9023],
        [0.7278, 0.7450, 0.8337, 0.1958],
        [0.8077, 0.3932, 0.8337, 0.9023],
        [0.6030, 0.3932, 0.8337, 0.1958],
        [0.4473, 0.9099, 0.4963, 0.4275],
        [0.3582, 0.9099, 0.8337, 0.4275],
        [0.7278, 0.7450, 0.4353, 0.0687],
        [0.8077, 0.7450, 0.4353, 0.9023],
        [0.7278, 0.9099, 0.4353, 0.4275],
        [0.3582, 0.9099, 0.8337, 0.4275]], grad_fn=<MaxBackward2>)
tensor([[0.8909, 0.6873, 0.6238, 0.1183],
        [0.9250, 0.6873, 0.6238, 0.1183],
        [0.8909, 0.6873, 0.6238, 0.1183],
        [0.9250, 0.4637, 0.5702, 0.1183],
        [0.9250, 0.3952, 0.3687, 0.1183],
        [

tensor([[0.8061, 0.7417, 0.4391, 0.9002],
        [0.4464, 0.5645, 0.8323, 0.1943],
        [0.6070, 0.5645, 0.4952, 0.0922],
        [0.7322, 0.7417, 0.8323, 0.1943],
        [0.7322, 0.7417, 0.4391, 0.0720],
        [0.7322, 0.7417, 0.4952, 0.0922],
        [0.8061, 0.9073, 0.3256, 0.9002],
        [0.7322, 0.9073, 0.4391, 0.4236],
        [0.6070, 0.3952, 0.8323, 0.1943],
        [0.3538, 0.9073, 0.8323, 0.4236],
        [0.8061, 0.3952, 0.8323, 0.9002],
        [0.8061, 0.9073, 0.3256, 0.9002],
        [0.4464, 0.9073, 0.4952, 0.4236],
        [0.6070, 0.3952, 0.8323, 0.1943],
        [0.8061, 0.5645, 0.4952, 0.9002],
        [0.7322, 0.7417, 0.4952, 0.0922],
        [0.3538, 0.9073, 0.8323, 0.4236],
        [0.8061, 0.3952, 0.8323, 0.9002]], grad_fn=<MaxBackward2>)
tensor([[0.8867, 0.3971, 0.3698, 0.6482],
        [0.9239, 0.6883, 0.6248, 0.1190],
        [0.9213, 0.4652, 0.5669, 0.1190],
        [0.8867, 0.8754, 0.8066, 0.3972],
        [0.8867, 0.4652, 0.5669, 0.6482],
        [

tensor([[0.6100, 0.5639, 0.4946, 0.0918],
        [0.7356, 0.7392, 0.8314, 0.1934],
        [0.3505, 0.9055, 0.8314, 0.4205],
        [0.7356, 0.9055, 0.4419, 0.4205],
        [0.7356, 0.7392, 0.4946, 0.0918],
        [0.8050, 0.3965, 0.8314, 0.8988],
        [0.8050, 0.9055, 0.3289, 0.8988],
        [0.8050, 0.9055, 0.3289, 0.8988],
        [0.8050, 0.7392, 0.4419, 0.8988],
        [0.4458, 0.5639, 0.8314, 0.1934],
        [0.4458, 0.9055, 0.4946, 0.4205],
        [0.3505, 0.9055, 0.8314, 0.4205],
        [0.6100, 0.3965, 0.8314, 0.1934],
        [0.7356, 0.7392, 0.4946, 0.0918],
        [0.7356, 0.7392, 0.4419, 0.0743],
        [0.8050, 0.5639, 0.4946, 0.8988],
        [0.8050, 0.3965, 0.8314, 0.8988],
        [0.6100, 0.3965, 0.8314, 0.1934]], grad_fn=<MaxBackward2>)
tensor([[0.9172, 0.4657, 0.5645, 0.1194],
        [0.8834, 0.8774, 0.8090, 0.3980],
        [0.4887, 0.9064, 0.9114, 0.3980],
        [0.4887, 0.8774, 0.8090, 0.6445],
        [0.8834, 0.6889, 0.6254, 0.1194],
        [

tensor([[0.3472, 0.3976, 0.8306, 0.1926],
        [0.9349, 0.9099, 0.9666, 0.3986]], grad_fn=<SelectBackward>)
    batch loss: 15.2909355164
  Train Loss: 15.2909355164
  Train Acc:  0
tensor([[0.7396, 0.7366, 0.4450, 0.0768],
        [0.3464, 0.9035, 0.8304, 0.4168],
        [0.6137, 0.3978, 0.8304, 0.1924],
        [0.7396, 0.7366, 0.8304, 0.1924],
        [0.8037, 0.7366, 0.4450, 0.8974],
        [0.8037, 0.9035, 0.3325, 0.8974],
        [0.8037, 0.9035, 0.3325, 0.8974],
        [0.4453, 0.5632, 0.8304, 0.1924],
        [0.7396, 0.7366, 0.4939, 0.0915],
        [0.4453, 0.9035, 0.4939, 0.4168],
        [0.8037, 0.5632, 0.4939, 0.8974],
        [0.7396, 0.9035, 0.4450, 0.4168],
        [0.8037, 0.3978, 0.8304, 0.8974],
        [0.7396, 0.7366, 0.4939, 0.0915],
        [0.8037, 0.3978, 0.8304, 0.8974],
        [0.3464, 0.9035, 0.8304, 0.4168],
        [0.6137, 0.3978, 0.8304, 0.1924],
        [0.6137, 0.5632, 0.4939, 0.0915]], grad_fn=<MaxBackward2>)
tensor([[0.8795, 0.4656, 0.5619, 0

tensor([[0.8028, 0.3987, 0.8298, 0.8965],
        [0.8028, 0.5628, 0.4935, 0.8965],
        [0.4450, 0.9022, 0.4935, 0.4139],
        [0.7427, 0.7346, 0.4473, 0.0785],
        [0.3434, 0.9022, 0.8298, 0.4139],
        [0.8028, 0.9022, 0.3352, 0.8965],
        [0.8028, 0.7346, 0.4473, 0.8965],
        [0.8028, 0.9022, 0.3352, 0.8965],
        [0.7427, 0.7346, 0.8298, 0.1917],
        [0.6164, 0.3987, 0.8298, 0.1917],
        [0.3434, 0.9022, 0.8298, 0.4139],
        [0.4450, 0.5628, 0.8298, 0.1917],
        [0.8028, 0.3987, 0.8298, 0.8965],
        [0.7427, 0.9022, 0.4473, 0.4139],
        [0.6164, 0.3987, 0.8298, 0.1917],
        [0.6164, 0.5628, 0.4935, 0.0913],
        [0.7427, 0.7346, 0.4935, 0.0913],
        [0.7427, 0.7346, 0.4935, 0.0913]], grad_fn=<MaxBackward2>)
tensor([[0.9341, 0.4004, 0.3716, 0.3992],
        [0.9221, 0.4004, 0.3716, 0.1199],
        [0.4918, 0.6898, 0.6265, 0.1199],
        [0.8764, 0.4650, 0.5600, 0.6369],
        [0.4918, 0.9141, 0.9150, 0.3992],
        [

tensor([[0.8018, 0.7324, 0.4499, 0.8956],
        [0.7465, 0.7324, 0.4931, 0.0911],
        [0.6197, 0.3998, 0.8291, 0.1909],
        [0.8018, 0.3998, 0.8291, 0.8956],
        [0.4446, 0.9008, 0.4931, 0.4102],
        [0.6197, 0.3998, 0.8291, 0.1909],
        [0.7465, 0.9008, 0.4499, 0.4102],
        [0.3397, 0.9008, 0.8291, 0.4102],
        [0.3397, 0.9008, 0.8291, 0.4102],
        [0.7465, 0.7324, 0.4931, 0.0911],
        [0.8018, 0.9008, 0.3382, 0.8956],
        [0.7465, 0.7324, 0.4499, 0.0805],
        [0.7465, 0.7324, 0.8291, 0.1909],
        [0.8018, 0.9008, 0.3382, 0.8956],
        [0.8018, 0.3998, 0.8291, 0.8956],
        [0.6197, 0.5624, 0.4931, 0.0911],
        [0.4446, 0.5624, 0.8291, 0.1909],
        [0.8018, 0.5624, 0.4931, 0.8956]], grad_fn=<MaxBackward2>)
tensor([[0.8727, 0.4013, 0.3721, 0.6338],
        [0.8727, 0.6902, 0.6269, 0.1202],
        [0.9033, 0.4637, 0.5579, 0.3996],
        [0.9335, 0.4013, 0.3721, 0.3996],
        [0.4932, 0.6902, 0.6269, 0.1202],
        [

tensor([[0.6229, 0.4007, 0.8284, 0.1901],
        [0.8010, 0.5621, 0.4927, 0.8948],
        [0.8010, 0.7304, 0.4523, 0.8948],
        [0.7501, 0.7304, 0.8284, 0.1901],
        [0.7501, 0.8995, 0.4523, 0.4066],
        [0.4444, 0.8995, 0.4927, 0.4066],
        [0.8010, 0.8995, 0.3410, 0.8948],
        [0.7501, 0.7304, 0.4927, 0.0909],
        [0.6229, 0.4007, 0.8284, 0.1901],
        [0.3364, 0.8995, 0.8284, 0.4066],
        [0.7501, 0.7304, 0.4523, 0.0821],
        [0.6229, 0.5621, 0.4927, 0.0909],
        [0.7501, 0.7304, 0.4927, 0.0909],
        [0.8010, 0.8995, 0.3410, 0.8948],
        [0.4444, 0.5621, 0.8284, 0.1901],
        [0.8010, 0.4007, 0.8284, 0.8948],
        [0.8010, 0.4007, 0.8284, 0.8948],
        [0.3364, 0.8995, 0.8284, 0.4066]], grad_fn=<MaxBackward2>)
tensor([[0.8986, 0.4620, 0.5560, 0.4000],
        [0.9212, 0.4020, 0.3726, 0.1203],
        [0.8692, 0.4020, 0.3726, 0.6315],
        [0.8692, 0.8843, 0.8170, 0.4000],
        [0.4943, 0.8843, 0.8170, 0.6315],
        [

tensor([[0.3338, 0.4013, 0.8280, 0.1896],
        [0.9328, 0.9250, 0.9787, 0.4003]], grad_fn=<SelectBackward>)
    batch loss: 10.3201141357
  Train Loss: 10.3201141357
  Train Acc:  0
tensor([[0.6259, 0.4015, 0.8278, 0.1895],
        [0.4441, 0.8984, 0.4924, 0.4030],
        [0.8002, 0.7286, 0.4546, 0.8941],
        [0.6259, 0.5617, 0.4924, 0.0908],
        [0.4441, 0.5617, 0.8278, 0.1895],
        [0.6259, 0.4015, 0.8278, 0.1895],
        [0.3332, 0.8984, 0.8278, 0.4030],
        [0.7535, 0.7286, 0.4924, 0.0908],
        [0.8002, 0.8984, 0.3436, 0.8941],
        [0.8002, 0.5617, 0.4924, 0.8941],
        [0.7535, 0.7286, 0.4924, 0.0908],
        [0.7535, 0.7286, 0.4546, 0.0836],
        [0.8002, 0.4015, 0.8278, 0.8941],
        [0.8002, 0.4015, 0.8278, 0.8941],
        [0.7535, 0.7286, 0.8278, 0.1895],
        [0.3332, 0.8984, 0.8278, 0.4030],
        [0.8002, 0.8984, 0.3436, 0.8941],
        [0.7535, 0.8984, 0.4546, 0.4030]], grad_fn=<MaxBackward2>)
tensor([[0.8942, 0.4600, 0.5542, 0

  Train Loss: 9.75223922729
  Train Acc:  0
tensor([[0.7997, 0.8976, 0.3456, 0.8936],
        [0.7561, 0.7272, 0.8274, 0.1889],
        [0.7997, 0.4021, 0.8274, 0.8936],
        [0.7561, 0.7272, 0.4921, 0.0907],
        [0.4440, 0.8976, 0.4921, 0.4000],
        [0.4440, 0.5615, 0.8274, 0.1889],
        [0.7997, 0.8976, 0.3456, 0.8936],
        [0.7997, 0.5615, 0.4921, 0.8936],
        [0.7561, 0.7272, 0.4562, 0.0847],
        [0.7997, 0.7272, 0.4562, 0.8936],
        [0.3308, 0.8976, 0.8274, 0.4000],
        [0.6282, 0.4021, 0.8274, 0.1889],
        [0.7997, 0.4021, 0.8274, 0.8936],
        [0.3308, 0.8976, 0.8274, 0.4000],
        [0.7561, 0.8976, 0.4562, 0.4000],
        [0.6282, 0.4021, 0.8274, 0.1889],
        [0.6282, 0.5615, 0.4921, 0.0907],
        [0.7561, 0.7272, 0.4921, 0.0907]], grad_fn=<MaxBackward2>)
tensor([[0.4962, 0.4032, 0.3732, 0.6677],
        [0.8630, 0.8865, 0.8198, 0.4006],
        [0.9325, 0.4032, 0.3732, 0.4006],
        [0.8630, 0.6911, 0.6278, 0.1205],
       

tensor([[0.4438, 0.8968, 0.4919, 0.3971],
        [0.7586, 0.8968, 0.4578, 0.3971],
        [0.6304, 0.4026, 0.8270, 0.1884],
        [0.7586, 0.7260, 0.4919, 0.0906],
        [0.7586, 0.7260, 0.4578, 0.0857],
        [0.7992, 0.7260, 0.4578, 0.8931],
        [0.7992, 0.5613, 0.4919, 0.8931],
        [0.7586, 0.7260, 0.8270, 0.1884],
        [0.7992, 0.4026, 0.8270, 0.8931],
        [0.7992, 0.8968, 0.3475, 0.8931],
        [0.6304, 0.5613, 0.4919, 0.0906],
        [0.3286, 0.8968, 0.8270, 0.3971],
        [0.4438, 0.5613, 0.8270, 0.1884],
        [0.7992, 0.8968, 0.3475, 0.8931],
        [0.6304, 0.4026, 0.8270, 0.1884],
        [0.3286, 0.8968, 0.8270, 0.3971],
        [0.7586, 0.7260, 0.4919, 0.0906],
        [0.7992, 0.4026, 0.8270, 0.8931]], grad_fn=<MaxBackward2>)
tensor([[0.4969, 0.6913, 0.6280, 0.1206],
        [0.4969, 0.8874, 0.8208, 0.6308],
        [0.8875, 0.4563, 0.5516, 0.4008],
        [0.8603, 0.6913, 0.6280, 0.1206],
        [0.8603, 0.4563, 0.5516, 0.6308],
        [

tensor([[0.7616, 0.7245, 0.4597, 0.0868],
        [0.6331, 0.4033, 0.8265, 0.1878],
        [0.3260, 0.8958, 0.8265, 0.3934],
        [0.7986, 0.4033, 0.8265, 0.8926],
        [0.6331, 0.5610, 0.4916, 0.0905],
        [0.7616, 0.7245, 0.8265, 0.1878],
        [0.7616, 0.7245, 0.4916, 0.0905],
        [0.7986, 0.8958, 0.3498, 0.8926],
        [0.7616, 0.7245, 0.4916, 0.0905],
        [0.3260, 0.8958, 0.8265, 0.3934],
        [0.7986, 0.8958, 0.3498, 0.8926],
        [0.7986, 0.5610, 0.4916, 0.8926],
        [0.7986, 0.4033, 0.8265, 0.8926],
        [0.7986, 0.7245, 0.4597, 0.8926],
        [0.6331, 0.4033, 0.8265, 0.1878],
        [0.4437, 0.8958, 0.4916, 0.3934],
        [0.4437, 0.5610, 0.8265, 0.1878],
        [0.7616, 0.8958, 0.4597, 0.3934]], grad_fn=<MaxBackward2>)
tensor([[0.8571, 0.4538, 0.5501, 0.6324],
        [0.8837, 0.4538, 0.5501, 0.4011],
        [0.4977, 0.9348, 0.9211, 0.4011],
        [0.9321, 0.4042, 0.3739, 0.4011],
        [0.8837, 0.4538, 0.5501, 0.1207],
        [

tensor([[0.7644, 0.7230, 0.4914, 0.0904],
        [0.3236, 0.8950, 0.8260, 0.3897],
        [0.4435, 0.8950, 0.4914, 0.3897],
        [0.7644, 0.8950, 0.4616, 0.3897],
        [0.6356, 0.5608, 0.4914, 0.0904],
        [0.7981, 0.8950, 0.3520, 0.8921],
        [0.7981, 0.4038, 0.8260, 0.8921],
        [0.7644, 0.7230, 0.4616, 0.0879],
        [0.7981, 0.8950, 0.3520, 0.8921],
        [0.7644, 0.7230, 0.4914, 0.0904],
        [0.6356, 0.4038, 0.8260, 0.1872],
        [0.6356, 0.4038, 0.8260, 0.1872],
        [0.7981, 0.7230, 0.4616, 0.8921],
        [0.7981, 0.5608, 0.4914, 0.8921],
        [0.3236, 0.8950, 0.8260, 0.3897],
        [0.7981, 0.4038, 0.8260, 0.8921],
        [0.7644, 0.7230, 0.8260, 0.1872],
        [0.4435, 0.5608, 0.8260, 0.1872]], grad_fn=<MaxBackward2>)
tensor([[0.8539, 0.6917, 0.6285, 0.1208],
        [0.4984, 0.9381, 0.9218, 0.4014],
        [0.4984, 0.6917, 0.6285, 0.1208],
        [0.4984, 0.8892, 0.8232, 0.6348],
        [0.8800, 0.4512, 0.5486, 0.1208],
        [

tensor([[0.4990, 0.9407, 0.9223, 0.4017],
        [0.4990, 0.4052, 0.3744, 0.6711],
        [0.8514, 0.8899, 0.8240, 0.4017],
        [0.8514, 0.6919, 0.6286, 0.1209],
        [0.4990, 0.6919, 0.6286, 0.1209],
        [0.8771, 0.4490, 0.5474, 0.1209],
        [0.8514, 0.4052, 0.3744, 0.6373],
        [0.8514, 0.6919, 0.6286, 0.1209],
        [0.9196, 0.4052, 0.3744, 0.1209],
        [0.8771, 0.4490, 0.5474, 0.4017],
        [0.4990, 0.4052, 0.3744, 0.6711],
        [0.9319, 0.4052, 0.3744, 0.4017],
        [0.9319, 0.4052, 0.3744, 0.4017],
        [0.9196, 0.6919, 0.6286, 0.1209],
        [0.8771, 0.4490, 0.5474, 0.4017],
        [0.8514, 0.4490, 0.5474, 0.6373],
        [0.4990, 0.9407, 0.9223, 0.4017],
        [0.4990, 0.8899, 0.8240, 0.6373]], grad_fn=<MinBackward2>)
tensor([ 0.0014, -8.4680, -0.0014, -0.0032,  1.5688, -0.1749, -0.1137, -0.0408,
        -6.4889, -0.0313, -0.0801,  0.0022,  0.3214,  3.0894, -0.0558, -0.3190,
         0.0010,  0.0317], grad_fn=<DivBackward1>)
tensor(7

  Train Loss: 7.51897907257
  Train Acc:  0
tensor([[0.7973, 0.7207, 0.4647, 0.8913],
        [0.7973, 0.8935, 0.3558, 0.8913],
        [0.7973, 0.8935, 0.3558, 0.8913],
        [0.6399, 0.5603, 0.4909, 0.0903],
        [0.4432, 0.5603, 0.8251, 0.1861],
        [0.7691, 0.8935, 0.4647, 0.3831],
        [0.6399, 0.4049, 0.8251, 0.1861],
        [0.6399, 0.4049, 0.8251, 0.1861],
        [0.3196, 0.8935, 0.8251, 0.3831],
        [0.4432, 0.8935, 0.4909, 0.3831],
        [0.7973, 0.4049, 0.8251, 0.8913],
        [0.7973, 0.4049, 0.8251, 0.8913],
        [0.3196, 0.8935, 0.8251, 0.3831],
        [0.7691, 0.7207, 0.4909, 0.0903],
        [0.7691, 0.7207, 0.4647, 0.0896],
        [0.7691, 0.7207, 0.8251, 0.1861],
        [0.7973, 0.5603, 0.4909, 0.8913],
        [0.7691, 0.7207, 0.4909, 0.0903]], grad_fn=<MaxBackward2>)
tensor([[0.8483, 0.4056, 0.3748, 0.6411],
        [0.4997, 0.4056, 0.3748, 0.6720],
        [0.4997, 0.4056, 0.3748, 0.6720],
        [0.8738, 0.4463, 0.5460, 0.1210],
       

tensor([-6.2511,  0.0010, -0.0270,  1.5323, -0.0631,  0.0018, -8.0158,  0.3034,
         0.0025, -0.0449, -0.0029, -0.2947, -0.1123, -0.0327, -0.1657,  2.9663,
         0.0138,  0.0017], grad_fn=<DivBackward1>)
tensor(7.1654, grad_fn=<MseLossBackward>)
tensor(5.8808e-06)
tensor([[0.3179, 0.4053, 0.8247, 0.1857],
        [0.9317, 0.9464, 0.9916, 0.4025]], grad_fn=<SelectBackward>)
    batch loss: 7.16543769836
  Train Loss: 7.16543769836
  Train Acc:  0
tensor([[0.4431, 0.5601, 0.8246, 0.1856],
        [0.7969, 0.8927, 0.3578, 0.8909],
        [0.7714, 0.7195, 0.4906, 0.0902],
        [0.7969, 0.7195, 0.4663, 0.8909],
        [0.7714, 0.8927, 0.4663, 0.3793],
        [0.7969, 0.8927, 0.3578, 0.8909],
        [0.6422, 0.4054, 0.8246, 0.1856],
        [0.6422, 0.5601, 0.4906, 0.0905],
        [0.3175, 0.8927, 0.8246, 0.3793],
        [0.7969, 0.5601, 0.4906, 0.8909],
        [0.6422, 0.4054, 0.8246, 0.1856],
        [0.7714, 0.7195, 0.8246, 0.1856],
        [0.7714, 0.7195, 0.4906, 0.0902

tensor(7.5302e-06)
tensor([[0.3164, 0.4057, 0.8243, 0.1852],
        [0.9317, 0.9490, 0.9927, 0.4029]], grad_fn=<SelectBackward>)
    batch loss: 6.9037103653
  Train Loss: 6.9037103653
  Train Acc:  0
tensor([[0.3160, 0.8921, 0.8242, 0.3764],
        [0.7966, 0.8921, 0.3594, 0.8906],
        [0.7732, 0.8921, 0.4676, 0.3764],
        [0.7966, 0.4058, 0.8242, 0.8906],
        [0.7966, 0.4058, 0.8242, 0.8906],
        [0.3160, 0.8921, 0.8242, 0.3764],
        [0.4430, 0.8921, 0.4904, 0.3764],
        [0.6438, 0.5599, 0.4904, 0.0921],
        [0.7732, 0.7186, 0.4904, 0.0902],
        [0.6438, 0.4058, 0.8242, 0.1851],
        [0.6438, 0.4058, 0.8242, 0.1851],
        [0.4430, 0.5599, 0.8242, 0.1851],
        [0.7732, 0.7186, 0.4676, 0.0921],
        [0.7732, 0.7186, 0.8242, 0.1851],
        [0.7732, 0.7186, 0.4904, 0.0902],
        [0.7966, 0.7186, 0.4676, 0.8906],
        [0.7966, 0.5599, 0.4904, 0.8906],
        [0.7966, 0.8921, 0.3594, 0.8906]], grad_fn=<MaxBackward2>)
tensor([[0.5009, 

tensor([[0.7749, 0.7177, 0.4689, 0.0943],
        [0.3145, 0.8915, 0.8239, 0.3734],
        [0.7963, 0.4062, 0.8239, 0.8903],
        [0.6455, 0.5597, 0.4903, 0.0943],
        [0.7749, 0.7177, 0.4903, 0.0901],
        [0.7963, 0.4062, 0.8239, 0.8903],
        [0.6455, 0.4062, 0.8239, 0.1846],
        [0.7963, 0.5597, 0.4903, 0.8903],
        [0.7963, 0.8915, 0.3609, 0.8903],
        [0.6455, 0.4062, 0.8239, 0.1846],
        [0.7749, 0.7177, 0.4903, 0.0901],
        [0.4428, 0.5597, 0.8239, 0.1846],
        [0.7963, 0.8915, 0.3609, 0.8903],
        [0.7963, 0.7177, 0.4689, 0.8903],
        [0.7749, 0.7177, 0.8239, 0.1846],
        [0.3145, 0.8915, 0.8239, 0.3734],
        [0.7749, 0.8915, 0.4689, 0.3734],
        [0.4428, 0.8915, 0.4903, 0.3734]], grad_fn=<MaxBackward2>)
tensor([[0.8406, 0.4389, 0.5424, 0.6531],
        [0.5014, 0.9522, 0.9243, 0.4034],
        [0.9316, 0.4068, 0.3756, 0.4034],
        [0.8659, 0.4389, 0.5424, 0.1212],
        [0.8406, 0.6927, 0.6295, 0.1212],
        [

tensor([[0.7959, 0.7167, 0.4705, 0.8899],
        [0.3127, 0.8908, 0.8234, 0.3697],
        [0.7768, 0.7167, 0.8234, 0.1841],
        [0.7768, 0.7167, 0.4705, 0.0975],
        [0.7959, 0.4067, 0.8234, 0.8899],
        [0.7768, 0.8908, 0.4705, 0.3697],
        [0.7959, 0.4067, 0.8234, 0.8899],
        [0.7959, 0.8908, 0.3628, 0.8899],
        [0.7768, 0.7167, 0.4900, 0.0900],
        [0.4427, 0.5595, 0.8234, 0.1841],
        [0.6473, 0.4067, 0.8234, 0.1841],
        [0.7768, 0.7167, 0.4900, 0.0900],
        [0.6473, 0.5595, 0.4900, 0.0975],
        [0.6473, 0.4067, 0.8234, 0.1841],
        [0.7959, 0.5595, 0.4900, 0.8899],
        [0.4427, 0.8908, 0.4900, 0.3697],
        [0.3127, 0.8908, 0.8234, 0.3697],
        [0.7959, 0.8908, 0.3628, 0.8899]], grad_fn=<MaxBackward2>)
tensor([[0.8377, 0.4072, 0.3759, 0.6583],
        [0.5020, 0.9554, 0.9248, 0.4040],
        [0.8377, 0.8928, 0.8282, 0.4040],
        [0.8377, 0.4359, 0.5411, 0.6583],
        [0.9315, 0.4072, 0.3759, 0.4040],
        [

tensor([[0.7786, 0.8901, 0.4720, 0.3660],
        [0.3110, 0.8901, 0.8230, 0.3660],
        [0.4426, 0.5592, 0.8230, 0.1835],
        [0.7956, 0.7157, 0.4720, 0.8895],
        [0.7786, 0.7157, 0.4898, 0.0900],
        [0.7956, 0.8901, 0.3646, 0.8895],
        [0.7786, 0.7157, 0.8230, 0.1835],
        [0.6489, 0.4072, 0.8230, 0.1835],
        [0.6489, 0.5592, 0.4898, 0.1007],
        [0.6489, 0.4072, 0.8230, 0.1835],
        [0.3110, 0.8901, 0.8230, 0.3660],
        [0.7956, 0.4072, 0.8230, 0.8895],
        [0.7956, 0.5592, 0.4898, 0.8895],
        [0.7786, 0.7157, 0.4898, 0.0900],
        [0.4426, 0.8901, 0.4898, 0.3660],
        [0.7786, 0.7157, 0.4720, 0.1007],
        [0.7956, 0.8901, 0.3646, 0.8895],
        [0.7956, 0.4072, 0.8230, 0.8895]], grad_fn=<MaxBackward2>)
tensor([[0.5026, 0.8931, 0.8290, 0.6636],
        [0.5026, 0.9587, 0.9253, 0.4047],
        [0.9181, 0.6931, 0.6299, 0.1213],
        [0.8350, 0.4077, 0.3762, 0.6636],
        [0.8350, 0.6931, 0.6299, 0.1213],
        [

tensor([[0.3093, 0.8894, 0.8225, 0.3623],
        [0.6504, 0.4077, 0.8225, 0.1829],
        [0.6504, 0.4077, 0.8225, 0.1829],
        [0.7800, 0.7148, 0.4735, 0.1038],
        [0.7800, 0.7148, 0.4895, 0.0899],
        [0.7953, 0.7148, 0.4735, 0.8892],
        [0.4424, 0.8894, 0.4895, 0.3623],
        [0.4424, 0.5590, 0.8225, 0.1829],
        [0.7800, 0.7148, 0.4895, 0.0899],
        [0.3093, 0.8894, 0.8225, 0.3623],
        [0.7800, 0.8894, 0.4735, 0.3623],
        [0.6504, 0.5590, 0.4895, 0.1038],
        [0.7953, 0.8894, 0.3664, 0.8892],
        [0.7953, 0.4077, 0.8225, 0.8892],
        [0.7953, 0.5590, 0.4895, 0.8892],
        [0.7953, 0.4077, 0.8225, 0.8892],
        [0.7800, 0.7148, 0.8225, 0.1829],
        [0.7953, 0.8894, 0.3664, 0.8892]], grad_fn=<MaxBackward2>)
tensor([[0.5032, 0.9620, 0.9258, 0.4054],
        [0.8589, 0.4296, 0.5387, 0.4054],
        [0.8589, 0.4296, 0.5387, 0.4054],
        [0.8323, 0.4296, 0.5387, 0.6689],
        [0.8323, 0.6933, 0.6301, 0.1214],
        [

tensor([[0.6516, 0.4081, 0.8221, 0.1824],
        [0.7950, 0.4081, 0.8221, 0.8889],
        [0.4423, 0.5588, 0.8221, 0.1824],
        [0.7811, 0.7139, 0.4750, 0.1066],
        [0.7950, 0.4081, 0.8221, 0.8889],
        [0.7950, 0.7139, 0.4750, 0.8889],
        [0.7950, 0.8887, 0.3681, 0.8889],
        [0.6516, 0.4081, 0.8221, 0.1824],
        [0.3077, 0.8887, 0.8221, 0.3586],
        [0.7811, 0.7139, 0.8221, 0.1824],
        [0.7811, 0.7139, 0.4893, 0.0898],
        [0.7811, 0.7139, 0.4893, 0.0898],
        [0.7950, 0.8887, 0.3681, 0.8889],
        [0.6516, 0.5588, 0.4893, 0.1066],
        [0.7950, 0.5588, 0.4893, 0.8889],
        [0.3077, 0.8887, 0.8221, 0.3586],
        [0.4423, 0.8887, 0.4893, 0.3586],
        [0.7811, 0.8887, 0.4750, 0.3586]], grad_fn=<MaxBackward2>)
tensor([[0.8571, 0.4263, 0.5376, 0.4062],
        [0.9314, 0.4085, 0.3767, 0.4062],
        [0.9177, 0.6935, 0.6303, 0.1215],
        [0.8299, 0.4263, 0.5376, 0.6740],
        [0.9314, 0.4085, 0.3767, 0.4062],
        [

tensor([[0.7817, 0.7130, 0.8217, 0.1818],
        [0.7947, 0.4086, 0.8217, 0.8885],
        [0.7817, 0.7130, 0.4765, 0.1091],
        [0.3061, 0.8881, 0.8217, 0.3550],
        [0.6527, 0.5586, 0.4891, 0.1091],
        [0.7947, 0.5586, 0.4891, 0.8885],
        [0.7947, 0.4086, 0.8217, 0.8885],
        [0.6527, 0.4086, 0.8217, 0.1818],
        [0.4422, 0.8881, 0.4891, 0.3550],
        [0.3061, 0.8881, 0.8217, 0.3550],
        [0.7817, 0.7130, 0.4891, 0.0898],
        [0.7947, 0.8881, 0.3699, 0.8885],
        [0.6527, 0.4086, 0.8217, 0.1818],
        [0.4422, 0.5586, 0.8217, 0.1818],
        [0.7817, 0.7130, 0.4891, 0.0898],
        [0.7947, 0.7130, 0.4765, 0.8885],
        [0.7817, 0.8881, 0.4765, 0.3550],
        [0.7947, 0.8881, 0.3699, 0.8885]], grad_fn=<MaxBackward2>)
tensor([[0.8276, 0.8932, 0.8310, 0.4071],
        [0.9314, 0.4089, 0.3770, 0.4071],
        [0.8276, 0.4229, 0.5365, 0.6791],
        [0.5043, 0.9690, 0.9269, 0.4071],
        [0.8556, 0.4229, 0.5365, 0.1216],
        [

tensor([[0.4420, 0.5584, 0.8212, 0.1813],
        [0.4420, 0.8874, 0.4889, 0.3513],
        [0.6536, 0.4090, 0.8212, 0.1813],
        [0.3045, 0.8874, 0.8212, 0.3513],
        [0.6536, 0.5584, 0.4889, 0.1114],
        [0.7944, 0.8874, 0.3716, 0.8882],
        [0.7818, 0.7122, 0.4779, 0.1114],
        [0.7818, 0.7122, 0.8212, 0.1813],
        [0.7944, 0.8874, 0.3716, 0.8882],
        [0.7944, 0.5584, 0.4889, 0.8882],
        [0.7818, 0.7122, 0.4889, 0.0897],
        [0.7944, 0.4090, 0.8212, 0.8882],
        [0.3045, 0.8874, 0.8212, 0.3513],
        [0.7818, 0.7122, 0.4889, 0.0897],
        [0.7944, 0.4090, 0.8212, 0.8882],
        [0.6536, 0.4090, 0.8212, 0.1813],
        [0.7944, 0.7122, 0.4779, 0.8882],
        [0.7818, 0.8874, 0.4779, 0.3513]], grad_fn=<MaxBackward2>)
tensor([[0.9172, 0.6938, 0.6307, 0.1216],
        [0.5049, 0.6938, 0.6307, 0.1216],
        [0.8544, 0.4195, 0.5355, 0.4081],
        [0.5049, 0.9726, 0.9274, 0.4081],
        [0.8544, 0.4195, 0.5355, 0.1216],
        [

tensor([[0.3032, 0.4093, 0.8209, 0.1808],
        [0.9313, 0.9756, 0.9984, 0.4089]], grad_fn=<SelectBackward>)
    batch loss: 5.02128314972
  Train Loss: 5.02128314972
  Train Acc:  0
tensor([[0.7942, 0.7115, 0.4794, 0.8879],
        [0.7815, 0.7115, 0.4886, 0.0896],
        [0.7942, 0.8868, 0.3732, 0.8879],
        [0.6542, 0.5582, 0.4886, 0.1133],
        [0.7942, 0.4094, 0.8208, 0.8879],
        [0.6542, 0.4094, 0.8208, 0.1807],
        [0.4419, 0.5582, 0.8208, 0.1807],
        [0.7815, 0.7115, 0.4886, 0.0896],
        [0.7942, 0.5582, 0.4886, 0.8879],
        [0.7815, 0.7115, 0.8208, 0.1807],
        [0.7815, 0.7115, 0.4794, 0.1133],
        [0.7815, 0.8868, 0.4794, 0.3477],
        [0.6542, 0.4094, 0.8208, 0.1807],
        [0.3028, 0.8868, 0.8208, 0.3477],
        [0.7942, 0.4094, 0.8208, 0.8879],
        [0.3028, 0.8868, 0.8208, 0.3477],
        [0.7942, 0.8868, 0.3732, 0.8879],
        [0.4419, 0.8868, 0.4886, 0.3477]], grad_fn=<MaxBackward2>)
tensor([[0.8239, 0.4096, 0.3776, 0

tensor([[0.7809, 0.7109, 0.8205, 0.1803],
        [0.3015, 0.8863, 0.8205, 0.3448],
        [0.7940, 0.4098, 0.8205, 0.8877],
        [0.7809, 0.7109, 0.4806, 0.1147],
        [0.6547, 0.4098, 0.8205, 0.1803],
        [0.4418, 0.5580, 0.8205, 0.1803],
        [0.7940, 0.8863, 0.3745, 0.8877],
        [0.7809, 0.7109, 0.4885, 0.0896],
        [0.7940, 0.8863, 0.3745, 0.8877],
        [0.7940, 0.5580, 0.4885, 0.8877],
        [0.7940, 0.7109, 0.4806, 0.8877],
        [0.7940, 0.4098, 0.8205, 0.8877],
        [0.7809, 0.8863, 0.4806, 0.3448],
        [0.6547, 0.4098, 0.8205, 0.1803],
        [0.7809, 0.7109, 0.4885, 0.0896],
        [0.4418, 0.8863, 0.4885, 0.3448],
        [0.3015, 0.8863, 0.8205, 0.3448],
        [0.6547, 0.5580, 0.4885, 0.1147]], grad_fn=<MaxBackward2>)
tensor([[0.8227, 0.8915, 0.8327, 0.4100],
        [0.5058, 0.9794, 0.9286, 0.4100],
        [0.9313, 0.4099, 0.3778, 0.4100],
        [0.8227, 0.4131, 0.5338, 0.6949],
        [0.8528, 0.4131, 0.5338, 0.4100],
        [

tensor([[0.3002, 0.4101, 0.8202, 0.1799],
        [0.9313, 0.9826, 0.9986, 0.4109]], grad_fn=<SelectBackward>)
    batch loss: 4.70714759827
  Train Loss: 4.70714759827
  Train Acc:  0
tensor([[0.7937, 0.5578, 0.4883, 0.8874],
        [0.2998, 0.8857, 0.8201, 0.3413],
        [0.2998, 0.8857, 0.8201, 0.3413],
        [0.7800, 0.7102, 0.4821, 0.1162],
        [0.7937, 0.4102, 0.8201, 0.8874],
        [0.4417, 0.5578, 0.8201, 0.1798],
        [0.6551, 0.4102, 0.8201, 0.1798],
        [0.7800, 0.8857, 0.4821, 0.3413],
        [0.7937, 0.8857, 0.3761, 0.8874],
        [0.7800, 0.7102, 0.4883, 0.0895],
        [0.7800, 0.7102, 0.8201, 0.1798],
        [0.7937, 0.4102, 0.8201, 0.8874],
        [0.4417, 0.8857, 0.4883, 0.3413],
        [0.7800, 0.7102, 0.4883, 0.0895],
        [0.6551, 0.5578, 0.4883, 0.1162],
        [0.6551, 0.4102, 0.8201, 0.1798],
        [0.7937, 0.8857, 0.3761, 0.8874],
        [0.7937, 0.7102, 0.4821, 0.8874]], grad_fn=<MaxBackward2>)
tensor([[0.9166, 0.4103, 0.3781, 0

tensor([[0.7935, 0.8853, 0.3759, 0.8871],
        [0.7935, 0.4097, 0.8198, 0.8871],
        [0.4415, 0.8853, 0.4881, 0.3384],
        [0.7935, 0.4097, 0.8198, 0.8871],
        [0.6553, 0.5576, 0.4881, 0.1172],
        [0.6553, 0.4097, 0.8198, 0.1793],
        [0.2984, 0.8853, 0.8198, 0.3384],
        [0.7792, 0.7096, 0.4881, 0.0895],
        [0.4415, 0.5576, 0.8198, 0.1793],
        [0.7935, 0.8853, 0.3759, 0.8871],
        [0.7792, 0.7096, 0.4881, 0.0895],
        [0.7792, 0.7096, 0.8198, 0.1793],
        [0.6553, 0.4097, 0.8198, 0.1793],
        [0.7792, 0.7096, 0.4833, 0.1172],
        [0.7935, 0.5576, 0.4881, 0.8871],
        [0.2984, 0.8853, 0.8198, 0.3384],
        [0.7792, 0.8853, 0.4833, 0.3384],
        [0.7935, 0.7096, 0.4833, 0.8871]], grad_fn=<MaxBackward2>)
tensor([[0.5067, 0.4106, 0.3783, 0.6807],
        [0.9312, 0.4106, 0.3783, 0.4122],
        [0.5067, 0.6945, 0.6313, 0.1219],
        [0.9312, 0.4106, 0.3783, 0.4122],
        [0.8520, 0.4066, 0.5321, 0.1219],
        [

tensor([[0.7933, 0.4115, 0.8194, 0.8868],
        [0.6554, 0.5574, 0.4879, 0.1183],
        [0.7783, 0.8847, 0.4848, 0.3349],
        [0.7933, 0.8847, 0.3704, 0.8868],
        [0.7933, 0.4115, 0.8194, 0.8868],
        [0.2966, 0.8847, 0.8194, 0.3349],
        [0.6554, 0.4115, 0.8194, 0.1788],
        [0.4414, 0.8847, 0.4879, 0.3349],
        [0.2966, 0.8847, 0.8194, 0.3349],
        [0.7933, 0.7089, 0.4848, 0.8868],
        [0.7783, 0.7089, 0.4879, 0.0894],
        [0.6554, 0.4115, 0.8194, 0.1788],
        [0.7783, 0.7089, 0.4879, 0.0894],
        [0.7783, 0.7089, 0.8194, 0.1788],
        [0.7933, 0.5574, 0.4879, 0.8868],
        [0.7783, 0.7089, 0.4848, 0.1183],
        [0.7933, 0.8847, 0.3704, 0.8868],
        [0.4414, 0.5574, 0.8194, 0.1788]], grad_fn=<MaxBackward2>)
tensor([[0.9278, 0.4108, 0.3788, 0.4167],
        [0.8518, 0.4029, 0.5311, 0.1219],
        [0.5072, 0.8889, 0.8341, 0.6813],
        [0.5072, 0.4108, 0.3788, 0.6813],
        [0.9278, 0.4108, 0.3788, 0.4167],
        [

  Train Loss: 4.27940750122
  Train Acc:  0
tensor([[0.6553, 0.4108, 0.8190, 0.1783],
        [0.7775, 0.8841, 0.4864, 0.3314],
        [0.2947, 0.8841, 0.8190, 0.3314],
        [0.7775, 0.7082, 0.4864, 0.1193],
        [0.7931, 0.4108, 0.8190, 0.8866],
        [0.7931, 0.4108, 0.8190, 0.8866],
        [0.7775, 0.7082, 0.8190, 0.1783],
        [0.7931, 0.8841, 0.3667, 0.8866],
        [0.4413, 0.8841, 0.4877, 0.3314],
        [0.7775, 0.7082, 0.4877, 0.0894],
        [0.7931, 0.5572, 0.4877, 0.8866],
        [0.7775, 0.7082, 0.4877, 0.0894],
        [0.7931, 0.7082, 0.4864, 0.8866],
        [0.6553, 0.5572, 0.4877, 0.1193],
        [0.4413, 0.5572, 0.8190, 0.1783],
        [0.7931, 0.8841, 0.3667, 0.8866],
        [0.2947, 0.8841, 0.8190, 0.3314],
        [0.6553, 0.4108, 0.8190, 0.1783]], grad_fn=<MaxBackward2>)
tensor([[0.8519, 0.3992, 0.5301, 0.4208],
        [0.5077, 0.8879, 0.8345, 0.6819],
        [0.5077, 0.9953, 0.9317, 0.4208],
        [0.8180, 0.3992, 0.5301, 0.7149],
       

tensor([[0.7928, 0.5570, 0.4875, 0.8863],
        [0.7928, 0.4102, 0.8186, 0.8863],
        [0.2926, 0.8836, 0.8186, 0.3279],
        [0.7768, 0.8836, 0.4879, 0.3279],
        [0.7928, 0.8836, 0.3645, 0.8863],
        [0.7768, 0.7076, 0.4879, 0.1201],
        [0.7768, 0.7076, 0.4879, 0.0893],
        [0.4412, 0.8836, 0.4875, 0.3279],
        [0.6551, 0.4102, 0.8186, 0.1778],
        [0.7928, 0.4102, 0.8186, 0.8863],
        [0.7928, 0.8836, 0.3645, 0.8863],
        [0.7928, 0.7076, 0.4879, 0.8863],
        [0.6551, 0.5570, 0.4875, 0.1201],
        [0.4412, 0.5570, 0.8186, 0.1778],
        [0.7768, 0.7076, 0.4879, 0.0893],
        [0.7768, 0.7076, 0.8186, 0.1778],
        [0.2926, 0.8836, 0.8186, 0.3279],
        [0.6551, 0.4102, 0.8186, 0.1778]], grad_fn=<MaxBackward2>)
tensor([[0.9158, 0.4116, 0.3795, 0.1220],
        [0.9231, 0.4116, 0.3795, 0.4238],
        [0.5081, 0.9999, 0.9328, 0.4238],
        [0.5081, 0.8869, 0.8349, 0.6825],
        [0.5081, 0.4116, 0.3795, 0.6825],
        [

tensor([[0.7926, 0.8830, 0.3631, 0.8860],
        [0.7926, 0.4102, 0.8183, 0.8860],
        [0.7926, 0.5569, 0.4873, 0.8860],
        [0.7763, 0.7069, 0.4896, 0.0893],
        [0.6548, 0.4102, 0.8183, 0.1773],
        [0.7926, 0.8830, 0.3631, 0.8860],
        [0.7926, 0.4102, 0.8183, 0.8860],
        [0.4410, 0.8830, 0.4873, 0.3244],
        [0.7763, 0.7069, 0.4896, 0.1208],
        [0.7763, 0.7069, 0.8183, 0.1773],
        [0.6548, 0.4102, 0.8183, 0.1773],
        [0.2904, 0.8830, 0.8183, 0.3244],
        [0.4410, 0.5569, 0.8183, 0.1773],
        [0.7763, 0.8830, 0.4896, 0.3244],
        [0.7763, 0.7069, 0.4896, 0.0893],
        [0.6548, 0.5569, 0.4873, 0.1208],
        [0.7926, 0.7069, 0.4896, 0.8860],
        [0.2904, 0.8830, 0.8183, 0.3244]], grad_fn=<MaxBackward2>)
tensor([[0.5086, 0.4119, 0.3798, 0.6831],
        [0.9216, 0.4119, 0.3798, 0.4266],
        [0.9156, 0.4119, 0.3798, 0.1221],
        [0.8155, 0.6951, 0.6320, 0.1221],
        [0.8526, 0.3916, 0.5282, 0.4266],
        [

tensor([[0.7924, 0.8825, 0.3621, 0.8858],
        [0.4409, 0.5567, 0.8179, 0.1768],
        [0.6544, 0.4106, 0.8179, 0.1768],
        [0.7924, 0.4106, 0.8179, 0.8858],
        [0.7759, 0.7063, 0.4913, 0.1214],
        [0.7924, 0.7063, 0.4913, 0.8858],
        [0.4409, 0.8825, 0.4871, 0.3209],
        [0.2880, 0.8825, 0.8179, 0.3209],
        [0.7759, 0.7063, 0.8179, 0.1768],
        [0.7759, 0.8825, 0.4913, 0.3209],
        [0.7759, 0.7063, 0.4913, 0.0892],
        [0.7759, 0.7063, 0.4913, 0.0892],
        [0.2880, 0.8825, 0.8179, 0.3209],
        [0.7924, 0.4106, 0.8179, 0.8858],
        [0.7924, 0.5567, 0.4871, 0.8858],
        [0.6544, 0.4106, 0.8179, 0.1768],
        [0.7924, 0.8825, 0.3621, 0.8858],
        [0.6544, 0.5567, 0.4871, 0.1214]], grad_fn=<MaxBackward2>)
tensor([[0.5091, 0.4122, 0.3801, 0.6837],
        [0.9154, 0.6953, 0.6322, 0.1222],
        [0.8532, 0.3877, 0.5272, 0.4294],
        [0.9200, 0.4122, 0.3801, 0.4294],
        [0.8143, 0.3877, 0.5272, 0.7272],
        [

tensor([[0.7922, 0.5565, 0.4869, 0.8855],
        [0.2855, 0.8820, 0.8176, 0.3175],
        [0.7922, 0.8820, 0.3615, 0.8855],
        [0.6538, 0.5565, 0.4869, 0.1219],
        [0.6538, 0.4111, 0.8176, 0.1763],
        [0.4408, 0.8820, 0.4869, 0.3175],
        [0.7756, 0.7057, 0.8176, 0.1763],
        [0.7756, 0.7057, 0.4930, 0.1219],
        [0.7756, 0.7057, 0.4930, 0.0892],
        [0.7756, 0.8820, 0.4930, 0.3175],
        [0.7922, 0.4111, 0.8176, 0.8855],
        [0.2855, 0.8820, 0.8176, 0.3175],
        [0.7922, 0.4111, 0.8176, 0.8855],
        [0.7756, 0.7057, 0.4930, 0.0892],
        [0.7922, 0.8820, 0.3615, 0.8855],
        [0.4408, 0.5565, 0.8176, 0.1763],
        [0.7922, 0.7057, 0.4930, 0.8855],
        [0.6538, 0.4111, 0.8176, 0.1763]], grad_fn=<MaxBackward2>)
tensor([[0.9152, 0.4125, 0.3804, 0.1222],
        [0.5095, 1.0083, 0.9373, 0.4321],
        [0.5095, 0.4125, 0.3804, 0.6843],
        [0.8541, 0.3837, 0.5262, 0.1222],
        [0.8541, 0.3837, 0.5262, 0.4321],
        [

tensor([[0.7920, 0.4115, 0.8172, 0.8853],
        [0.7920, 0.8815, 0.3611, 0.8853],
        [0.6530, 0.5563, 0.4867, 0.1224],
        [0.6530, 0.4115, 0.8172, 0.1758],
        [0.4407, 0.5563, 0.8172, 0.1758],
        [0.7754, 0.7052, 0.4947, 0.1224],
        [0.4407, 0.8815, 0.4867, 0.3141],
        [0.7754, 0.8815, 0.4947, 0.3141],
        [0.7920, 0.8815, 0.3611, 0.8853],
        [0.6530, 0.4115, 0.8172, 0.1758],
        [0.7754, 0.7052, 0.4947, 0.0891],
        [0.7920, 0.4115, 0.8172, 0.8853],
        [0.2828, 0.8815, 0.8172, 0.3141],
        [0.7920, 0.5563, 0.4867, 0.8853],
        [0.7754, 0.7052, 0.4947, 0.0891],
        [0.7920, 0.7052, 0.4947, 0.8853],
        [0.2828, 0.8815, 0.8172, 0.3141],
        [0.7754, 0.7052, 0.8172, 0.1758]], grad_fn=<MaxBackward2>)
tensor([[0.9175, 0.4128, 0.3806, 0.4345],
        [0.5099, 0.4128, 0.3806, 0.6848],
        [0.8552, 0.3796, 0.5252, 0.1223],
        [0.8552, 0.3796, 0.5252, 0.4345],
        [0.9150, 0.6956, 0.6325, 0.1223],
        [

tensor([[0.2800, 0.8810, 0.8169, 0.3107],
        [0.7753, 0.7046, 0.4963, 0.0891],
        [0.6521, 0.4119, 0.8169, 0.1753],
        [0.7918, 0.5561, 0.4865, 0.8850],
        [0.7918, 0.8810, 0.3609, 0.8850],
        [0.4406, 0.8810, 0.4865, 0.3107],
        [0.2800, 0.8810, 0.8169, 0.3107],
        [0.7753, 0.7046, 0.4963, 0.1227],
        [0.7753, 0.8810, 0.4963, 0.3107],
        [0.7918, 0.4119, 0.8169, 0.8850],
        [0.6521, 0.5561, 0.4865, 0.1227],
        [0.7918, 0.8810, 0.3609, 0.8850],
        [0.7918, 0.7046, 0.4963, 0.8850],
        [0.7918, 0.4119, 0.8169, 0.8850],
        [0.7753, 0.7046, 0.4963, 0.0891],
        [0.7753, 0.7046, 0.8169, 0.1753],
        [0.6521, 0.4119, 0.8169, 0.1753],
        [0.4406, 0.5561, 0.8169, 0.1753]], grad_fn=<MaxBackward2>)
tensor([[0.5104, 1.0087, 0.9411, 0.4366],
        [0.8104, 0.6957, 0.6326, 0.1223],
        [0.8565, 0.3754, 0.5241, 0.4366],
        [0.9149, 0.4131, 0.3809, 0.1223],
        [0.5104, 0.4131, 0.3809, 0.6854],
        [

tensor([[0.7751, 0.7041, 0.4979, 0.1230],
        [0.2771, 0.8805, 0.8165, 0.3073],
        [0.7751, 0.7041, 0.8165, 0.1749],
        [0.4404, 0.5560, 0.8165, 0.1749],
        [0.7916, 0.4121, 0.8165, 0.8848],
        [0.7916, 0.7041, 0.4979, 0.8848],
        [0.7751, 0.8805, 0.4979, 0.3073],
        [0.6510, 0.5560, 0.4864, 0.1230],
        [0.6510, 0.4121, 0.8165, 0.1749],
        [0.7751, 0.7041, 0.4979, 0.0890],
        [0.4404, 0.8805, 0.4864, 0.3073],
        [0.2771, 0.8805, 0.8165, 0.3073],
        [0.6510, 0.4121, 0.8165, 0.1749],
        [0.7916, 0.5560, 0.4864, 0.8848],
        [0.7916, 0.8805, 0.3607, 0.8848],
        [0.7916, 0.8805, 0.3607, 0.8848],
        [0.7751, 0.7041, 0.4979, 0.0890],
        [0.7916, 0.4121, 0.8165, 0.8848]], grad_fn=<MaxBackward2>)
tensor([[0.8091, 0.3710, 0.5231, 0.7403],
        [0.5108, 1.0090, 0.9432, 0.4386],
        [0.8091, 0.8820, 0.8366, 0.4386],
        [0.9147, 0.6959, 0.6328, 0.1224],
        [0.9161, 0.4134, 0.3811, 0.4386],
        [

tensor([[0.7915, 0.4123, 0.8162, 0.8845],
        [0.7915, 0.5558, 0.4862, 0.8845],
        [0.6497, 0.4123, 0.8162, 0.1744],
        [0.4403, 0.8800, 0.4862, 0.3040],
        [0.7915, 0.4123, 0.8162, 0.8845],
        [0.7750, 0.8800, 0.4995, 0.3040],
        [0.2741, 0.8800, 0.8162, 0.3040],
        [0.7750, 0.7036, 0.4995, 0.0890],
        [0.7915, 0.8800, 0.3607, 0.8845],
        [0.7915, 0.8800, 0.3607, 0.8845],
        [0.7750, 0.7036, 0.8162, 0.1744],
        [0.2741, 0.8800, 0.8162, 0.3040],
        [0.7750, 0.7036, 0.4995, 0.1233],
        [0.7750, 0.7036, 0.4995, 0.0890],
        [0.6497, 0.4123, 0.8162, 0.1744],
        [0.6497, 0.5558, 0.4862, 0.1233],
        [0.7915, 0.7036, 0.4995, 0.8845],
        [0.4403, 0.5558, 0.8162, 0.1744]], grad_fn=<MaxBackward2>)
tensor([[0.9157, 0.4136, 0.3814, 0.4405],
        [0.9145, 0.4136, 0.3814, 0.1224],
        [0.8599, 0.3666, 0.5220, 0.4405],
        [0.5112, 0.6960, 0.6329, 0.1224],
        [0.9157, 0.4136, 0.3814, 0.4405],
        [

tensor([[0.6482, 0.4125, 0.8159, 0.1739],
        [0.6482, 0.4125, 0.8159, 0.1739],
        [0.7913, 0.5556, 0.4860, 0.8843],
        [0.6482, 0.5556, 0.4860, 0.1235],
        [0.4402, 0.8795, 0.4860, 0.3007],
        [0.7749, 0.7031, 0.5010, 0.0889],
        [0.7913, 0.4125, 0.8159, 0.8843],
        [0.7749, 0.7031, 0.5010, 0.0889],
        [0.2711, 0.8795, 0.8159, 0.3007],
        [0.7749, 0.7031, 0.8159, 0.1739],
        [0.7749, 0.7031, 0.5010, 0.1235],
        [0.7749, 0.8795, 0.5010, 0.3007],
        [0.2711, 0.8795, 0.8159, 0.3007],
        [0.7913, 0.8795, 0.3607, 0.8843],
        [0.4402, 0.5556, 0.8159, 0.1739],
        [0.7913, 0.4125, 0.8159, 0.8843],
        [0.7913, 0.7031, 0.5010, 0.8843],
        [0.7913, 0.8795, 0.3607, 0.8843]], grad_fn=<MaxBackward2>)
tensor([[0.8619, 0.3620, 0.5210, 0.4423],
        [0.8619, 0.3620, 0.5210, 0.4423],
        [0.9143, 0.4139, 0.3816, 0.1225],
        [0.8619, 0.3620, 0.5210, 0.1225],
        [0.5117, 0.6961, 0.6331, 0.1225],
        [